version: '3.1'

services:
  jupyter:
    container_name: jupyter_lab
    image: notebook
    build:
      context: ./notebook
    environment:
      - NOTEBOOK_USER=danpra # replace with your username
      - PYTHONUNBUFFERED=1
    ports:
      - 8888:8888
    volumes:
    - ./notebook/projects:/home/${NOTEBOOK_USER:-/danpra}/project
    #- ./notebook/neomodel:/opt/conda/lib/python3.7/site-packages/neomodel #neomodel support for neo4j 4.x
    depends_on:
      - neo4j
    networks: 
      - net
  neo4j:
    container_name: neo4j
    image: neo4j:3.5.14
    environment:
      - NEO4J_AUTH=none #neo4j/test
      - NEO4J_dbms_memory_pagecache_size=1G #default 512M
      - NEO4J_dbms_security_procedures_unrestricted=apoc.\\\*
      - NE04J_dbms.security.procedures.unrestricted=algo.\\\*
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
      - ./neo4j/conf:/var/lib/neo4j/conf
    networks: 
      - net

networks:
  net:
    driver: bridge
    
volumes:
  data:
  logs:
  conf:
  neomodal:
  projects:

